// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObjectBusiness;

#nullable disable

namespace ObjectBusiness.Migrations
{
    [DbContext(typeof(BackToMeDbContext))]
    partial class BackToMeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObjectBusiness.CategoryPost", b =>
                {
                    b.Property<int>("CategoryPostId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryPostName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryPostId");

                    b.ToTable("CategoryPost");

                    b.HasData(
                        new
                        {
                            CategoryPostId = 781275554,
                            CategoryPostName = "IPhone",
                            CreatedAt = new DateTime(2026, 7, 25, 14, 44, 15, 852, DateTimeKind.Local).AddTicks(3499)
                        },
                        new
                        {
                            CategoryPostId = 171705011,
                            CategoryPostName = "IPad",
                            CreatedAt = new DateTime(2026, 7, 25, 14, 44, 15, 852, DateTimeKind.Local).AddTicks(3503)
                        },
                        new
                        {
                            CategoryPostId = 357308849,
                            CategoryPostName = "Chromebook",
                            CreatedAt = new DateTime(2026, 7, 25, 14, 44, 15, 852, DateTimeKind.Local).AddTicks(3532)
                        },
                        new
                        {
                            CategoryPostId = 663701472,
                            CategoryPostName = "Earbuds",
                            CreatedAt = new DateTime(2026, 7, 25, 14, 44, 15, 852, DateTimeKind.Local).AddTicks(3537)
                        },
                        new
                        {
                            CategoryPostId = 1270846585,
                            CategoryPostName = "Wallet",
                            CreatedAt = new DateTime(2026, 7, 25, 14, 44, 15, 852, DateTimeKind.Local).AddTicks(3541)
                        },
                        new
                        {
                            CategoryPostId = 2145456831,
                            CategoryPostName = "Charger",
                            CreatedAt = new DateTime(2026, 7, 25, 14, 44, 15, 852, DateTimeKind.Local).AddTicks(3545)
                        });
                });

            modelBuilder.Entity("ObjectBusiness.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAId")
                        .HasColumnType("int");

                    b.Property<int>("UserALastReadMessageId")
                        .HasColumnType("int");

                    b.Property<int>("UserBId")
                        .HasColumnType("int");

                    b.Property<int>("UserBLastReadMessageId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserAId");

                    b.HasIndex("UserBId");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("ObjectBusiness.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstitutionAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InstitutionId");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("ObjectBusiness.InstitutionRequest", b =>
                {
                    b.Property<int>("InstitutionRequestId")
                        .HasColumnType("int");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimatedPopulation")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerifiedEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedInstitution")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedWebsite")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WebsiteVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstitutionRequestId");

                    b.ToTable("InstitutionRequests");
                });

            modelBuilder.Entity("ObjectBusiness.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoundPostId")
                        .HasColumnType("int");

                    b.Property<int>("LostPostId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MatchId");

                    b.HasIndex("FoundPostId");

                    b.HasIndex("LostPostId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("ObjectBusiness.MessageChat", b =>
                {
                    b.Property<int>("MessageChatId")
                        .HasColumnType("int");

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserSenderId")
                        .HasColumnType("int");

                    b.HasKey("MessageChatId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserSenderId");

                    b.ToTable("MessageChat");
                });

            modelBuilder.Entity("ObjectBusiness.Notifications", b =>
                {
                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostMatchedId")
                        .HasColumnType("int");

                    b.Property<int>("PostOriginalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationId");

                    b.HasIndex("PostMatchedId");

                    b.HasIndex("PostOriginalId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ObjectBusiness.PickUpRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PickUpDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.HasIndex("PostId");

                    b.ToTable("PickUpRequest");
                });

            modelBuilder.Entity("ObjectBusiness.Posts", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryPostId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsReceived")
                        .HasColumnType("bit");

                    b.Property<int?>("OldUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Vector")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.HasIndex("CategoryPostId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ObjectBusiness.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("ObjectBusiness.TransferRequests", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("PostId");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("ObjectBusiness.Users", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAgreedToTerms")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedEmail")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickImage1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickImage2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 2043193290,
                            Avatar = "avatar_CV.jpg",
                            CreatedAt = new DateTime(2026, 7, 25, 14, 44, 15, 852, DateTimeKind.Local).AddTicks(3191),
                            DateOfBirth = new DateTime(2007, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mycampuslostfound@gmail.com",
                            FirstName = "System",
                            IsActive = true,
                            IsAgreedToTerms = true,
                            IsVerifiedEmail = true,
                            LastName = "Admin",
                            Password = "$2a$11$92uWViLQUKTIVIADFxhzqe39tDMoLWJX5e1FyXaeedfrq5CoMAGQ6",
                            PickImage1 = "1",
                            PickImage2 = "12",
                            Role = "SystemAdmin"
                        });
                });

            modelBuilder.Entity("ObjectBusiness.VerificationCode", b =>
                {
                    b.Property<int>("VerificationCodeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VerificationCodeId");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("VerificationCode");
                });

            modelBuilder.Entity("ObjectBusiness.Chat", b =>
                {
                    b.HasOne("ObjectBusiness.Posts", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObjectBusiness.Users", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ObjectBusiness.Users", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("ObjectBusiness.Match", b =>
                {
                    b.HasOne("ObjectBusiness.Posts", "FoundPost")
                        .WithMany()
                        .HasForeignKey("FoundPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ObjectBusiness.Posts", "LostPost")
                        .WithMany()
                        .HasForeignKey("LostPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FoundPost");

                    b.Navigation("LostPost");
                });

            modelBuilder.Entity("ObjectBusiness.MessageChat", b =>
                {
                    b.HasOne("ObjectBusiness.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ObjectBusiness.Users", "UserSender")
                        .WithMany()
                        .HasForeignKey("UserSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("UserSender");
                });

            modelBuilder.Entity("ObjectBusiness.Notifications", b =>
                {
                    b.HasOne("ObjectBusiness.Posts", "PostMatched")
                        .WithMany()
                        .HasForeignKey("PostMatchedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ObjectBusiness.Posts", "PostOriginal")
                        .WithMany()
                        .HasForeignKey("PostOriginalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PostMatched");

                    b.Navigation("PostOriginal");
                });

            modelBuilder.Entity("ObjectBusiness.PickUpRequest", b =>
                {
                    b.HasOne("ObjectBusiness.Posts", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ObjectBusiness.Posts", b =>
                {
                    b.HasOne("ObjectBusiness.CategoryPost", "CategoryPost")
                        .WithMany()
                        .HasForeignKey("CategoryPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObjectBusiness.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ObjectBusiness.Student", b =>
                {
                    b.HasOne("ObjectBusiness.Users", "User")
                        .WithOne("Student")
                        .HasForeignKey("ObjectBusiness.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ObjectBusiness.TransferRequests", b =>
                {
                    b.HasOne("ObjectBusiness.Posts", "Post")
                        .WithMany("TransferRequests")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ObjectBusiness.Users", b =>
                {
                    b.HasOne("ObjectBusiness.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("ObjectBusiness.VerificationCode", b =>
                {
                    b.HasOne("ObjectBusiness.Match", "Match")
                        .WithOne("VerificationCode")
                        .HasForeignKey("ObjectBusiness.VerificationCode", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ObjectBusiness.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ObjectBusiness.Institution", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ObjectBusiness.Match", b =>
                {
                    b.Navigation("VerificationCode");
                });

            modelBuilder.Entity("ObjectBusiness.Posts", b =>
                {
                    b.Navigation("TransferRequests");
                });

            modelBuilder.Entity("ObjectBusiness.Users", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
